### ISSUE TITLE
quotes should match

### ISSUE THREAD

**Issue by aric87** [crtnywllr/api-hack#1]
https://github.com/crtnywllr/api-hack/blob/master/index.html#L10

**Comment by aric87** [comment]
https://github.com/crtnywllr/api-hack/blob/master/index.html#L401

**Comment by aric87** [comment]
https://github.com/crtnywllr/api-hack/blob/master/index.html#L411

**Comment by aric87** [comment]
https://github.com/crtnywllr/api-hack/blob/master/css/style.css#L62
css has some single, some double. doesn't matter which, just make sure it's consistent

**Comment by crtnywllr** [comment]
commit ```f354578e7e164876d250f2a517fdefc62e36cc71```
